times = ('Atlético-MG', 'Flamengo', 'Palmeiras', 'Fortaleza', 'Fortaleza', 'RB Bragantino', 'Fluminense', 'América-MG',  'Atlético-GO', 'Santos', 'Ceará', 'Internacional', 'São Paulo', 'Athletico-PR', 'Cuiabá', 'Juventude', 'Grêmio', 'Bahia', 'Sport', 'Chapecoense')
print('-=' * 20)
print(f'Lista de times do Brasileirão: {times}')
print('-=' * 20)
print(f'Os 5 primeros são: {times[0:5]}')
print('-=' * 20)
print(f'Os 4 ultimos são: {times[-4:]}')
print('-=' * 20)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 20)
print(f'O Chapecoense está em {times.index("Chapecoense") + 1}ª posição')